# Generated by Django 5.1.2 on 2024-10-14 03:30

import banjo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', banjo.models.StringField(default='')),
                ('artist', banjo.models.StringField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
