# Generated by Django 5.1.2 on 2024-10-15 06:59

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_song_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='description',
            field=banjo.models.StringField(default=''),
        ),
    ]
