# Generated by Django 5.1.2 on 2024-10-15 07:09

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_song_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='Happy',
            field=banjo.models.BooleanField(default=False),
        ),
    ]
