# Generated by Django 5.1.2 on 2024-10-15 07:11

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_song_happy'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='Angry',
            field=banjo.models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='Love',
            field=banjo.models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='Sad',
            field=banjo.models.BooleanField(default=False),
        ),
    ]
