# Generated by Django 5.1.2 on 2024-10-15 07:12

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_song_angry_song_love_song_sad'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='Calm',
            field=banjo.models.BooleanField(default=False),
        ),
    ]
