# Generated by Django 5.1.2 on 2024-10-15 07:20

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_song_calm'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='Energetic',
            field=banjo.models.BooleanField(default=False),
        ),
    ]
